/**
 * WCLoner Platform Integration
 * Client-side navigation and link interception for downloaded websites
 */
(function() {
  'use strict';

  // Configuration (auto-generated by WCLoner)
  const CONFIG = {
    mainDomain: '{{MAIN_DOMAIN}}',      // example.com
    localDomain: '{{LOCAL_DOMAIN}}',    // example.local
    subdomains: {{SUBDOMAINS_JSON}}     // ['sub1.example.com', 'sub2.example.com']
  };

  // Detect mode
  const isProd = window.location.hostname.endsWith('.' + CONFIG.localDomain) || 
                 window.location.hostname === CONFIG.localDomain;
  const isLocalhost = window.location.hostname === 'localhost' || 
                      window.location.hostname.startsWith('127.0.0.1');

  console.log('[WCLoner] Platform integration loaded', {
    mode: isProd ? 'production' : 'localhost',
    domain: window.location.hostname
  });

  // Wait for DOM ready
  function ready(fn) {
    if (document.readyState !== 'loading') {
      fn();
    } else {
      document.addEventListener('DOMContentLoaded', fn);
    }
  }

  // Convert absolute URL to local URL
  function convertToLocal(href) {
    try {
      const url = new URL(href, window.location.href);
      const hostname = url.hostname;
      
      // Check if it's one of our domains
      const isMainDomain = hostname === CONFIG.mainDomain || hostname === 'www.' + CONFIG.mainDomain;
      const isSubdomain = CONFIG.subdomains.some(sub => hostname === sub);
      
      if (isMainDomain || isSubdomain) {
        // Convert to local domain
        const localHost = hostname.replace(CONFIG.mainDomain, CONFIG.localDomain);
        
        if (isProd || isLocalhost) {
          // Keep protocol-relative or use current protocol
          return '//' + localHost + url.pathname + url.search + url.hash;
        }
      }
      
      return null; // External link, don't convert
    } catch (e) {
      return null;
    }
  }

  // Intercept clicks on links
  function interceptLinks() {
    document.addEventListener('click', function(e) {
      // Find the link element (support shadow DOM)
      let link = null;
      const path = e.composedPath ? e.composedPath() : [e.target];
      
      for (let i = 0; i < path.length; i++) {
        if (path[i].tagName === 'A') {
          link = path[i];
          break;
        }
      }
      
      if (!link) link = e.target.closest('a');
      if (!link) return;

      const href = link.getAttribute('href') || '';

      // Skip special links
      if (!href || 
          href.startsWith('#') || 
          href.startsWith('javascript:') ||
          href.startsWith('mailto:') || 
          href.startsWith('tel:')) {
        return;
      }

      // Try to convert to local URL
      const localUrl = convertToLocal(href);
      
      if (localUrl) {
        e.preventDefault();
        
        // Remove target=_blank to avoid opening new tabs
        if (link.getAttribute('target') === '_blank') {
          link.removeAttribute('target');
        }
        
        // Navigate to local URL
        window.location.href = localUrl;
        
        console.log('[WCLoner] Intercepted:', href, '->', localUrl);
      }
    }, true); // Use capture phase to intercept before other handlers
  }

  // Fix form actions
  function fixForms() {
    document.querySelectorAll('form[action]').forEach(form => {
      const action = form.getAttribute('action');
      if (action && action.includes(CONFIG.mainDomain)) {
        const localAction = convertToLocal(action);
        if (localAction) {
          form.setAttribute('action', localAction);
          console.log('[WCLoner] Fixed form action:', action, '->', localAction);
        }
      }
    });
  }

  // Remove external trackers and analytics
  function blockTrackers() {
    // Block common tracker domains
    const blockedDomains = [
      'google-analytics.com',
      'googletagmanager.com',
      'facebook.net',
      'doubleclick.net',
      'cookielaw.org',
      'onetrust.com'
    ];

    // Intercept script creation
    const originalCreateElement = document.createElement.bind(document);
    document.createElement = function(tagName) {
      const element = originalCreateElement(tagName);
      
      if (tagName.toLowerCase() === 'script') {
        const originalSetAttribute = element.setAttribute.bind(element);
        element.setAttribute = function(name, value) {
          if (name === 'src' && typeof value === 'string') {
            // Block if matches blocked domains
            if (blockedDomains.some(domain => value.includes(domain))) {
              console.log('[WCLoner] Blocked tracker:', value);
              return;
            }
          }
          return originalSetAttribute(name, value);
        };
      }
      
      return element;
    };
  }

  // Initialize on DOM ready
  ready(function() {
    interceptLinks();
    fixForms();
    blockTrackers();
    
    console.log('[WCLoner] Platform integration initialized');
  });

  // Expose API for debugging
  window.WCLoner = {
    config: CONFIG,
    convertToLocal: convertToLocal,
    version: '1.0.0'
  };

})();
