#!/usr/bin/env node
/**
 * WCLoner Universal Server Template
 * Auto-generated server for downloaded websites
 * 
 * Features:
 * - Host-based routing (subdomain.site.local -> subdomain.site.com/)
 * - HTML URL rewriting (absolute -> relative)
 * - Platform integration script injection
 * - Static file serving with gzip
 * - CDN fallback support
 */

const http = require('http');
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

// ============================================================
// CONFIGURATION (auto-generated by WCLoner)
// ============================================================

const PORT = parseInt(process.env.PORT || '{{PORT}}', 10);
const BASE_DIR = __dirname;
const MAIN_DOMAIN = '{{MAIN_DOMAIN}}'; // example.com
const LOCAL_DOMAIN = '{{LOCAL_DOMAIN}}'; // example.local

// All subdomains found in this download
const SUBDOMAINS = {{SUBDOMAINS_JSON}};

console.log(`[WCLoner Server] Starting for ${MAIN_DOMAIN}`);
console.log(`[WCLoner Server] Found ${SUBDOMAINS.length} subdomains:`, SUBDOMAINS.join(', '));

// ============================================================
// HOST RESOLUTION
// ============================================================

function resolveFolder(host) {
  if (!host) return MAIN_DOMAIN;
  host = host.split(':')[0].toLowerCase();
  
  // Main domain: example.local -> example.com
  if (host === LOCAL_DOMAIN || host === 'www.' + LOCAL_DOMAIN) {
    return MAIN_DOMAIN;
  }
  
  // Subdomain: sub.example.local -> sub.example.com
  const localSuffix = '.' + LOCAL_DOMAIN;
  if (host.endsWith(localSuffix)) {
    const sub = host.replace(localSuffix, '');
    return sub + '.' + MAIN_DOMAIN;
  }
  
  // localhost -> main domain
  if (host === 'localhost' || host.startsWith('127.0.0.1')) {
    return MAIN_DOMAIN;
  }
  
  return MAIN_DOMAIN;
}

// ============================================================
// MIME TYPES
// ============================================================

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.htm': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.json': 'application/json',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.ttf': 'font/ttf',
  '.eot': 'application/vnd.ms-fontobject',
  '.otf': 'font/otf',
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  '.xml': 'application/xml',
  '.txt': 'text/plain',
  '.map': 'application/json',
};

function getContentType(filePath) {
  const ext = path.extname(filePath.split('?')[0]).toLowerCase();
  return MIME_TYPES[ext] || 'application/octet-stream';
}

// ============================================================
// HTML REWRITING
// ============================================================

function rewriteHtml(html, currentFolder) {
  // 1. Rewrite absolute URLs to relative
  const mainDomainEsc = MAIN_DOMAIN.replace(/\./g, '\\.');
  
  // https://example.com/path -> /path
  html = html.replace(new RegExp(`https?://${mainDomainEsc}/`, 'g'), '/');
  
  // Rewrite subdomains: https://sub.example.com/path -> //sub.example.local/path
  SUBDOMAINS.forEach(sub => {
    const subEsc = sub.replace(/\./g, '\\.');
    const localSub = sub.replace('.' + MAIN_DOMAIN, '.' + LOCAL_DOMAIN);
    html = html.replace(new RegExp(`https?://${subEsc}/`, 'g'), `//${localSub}/`);
  });
  
  // 2. Remove external trackers and analytics
  html = html.replace(/<script[^>]*src="[^"]*google-analytics[^"]*"[^>]*><\/script>/gi, '');
  html = html.replace(/<script[^>]*src="[^"]*googletagmanager[^"]*"[^>]*><\/script>/gi, '');
  html = html.replace(/<script[^>]*src="[^"]*facebook\.net[^"]*"[^>]*><\/script>/gi, '');
  html = html.replace(/<script[^>]*src="[^"]*cookielaw\.org[^"]*"[^>]*><\/script>/gi, '');
  
  // 3. Remove integrity and crossorigin attributes (break local files)
  html = html.replace(/\s+integrity="[^"]*"/gi, '');
  html = html.replace(/\s+crossorigin="[^"]*"/gi, '');
  html = html.replace(/\s+crossorigin\s/gi, ' ');
  
  // 4. Inject platform-integration.js before </head>
  if (!html.includes('platform-integration.js')) {
    html = html.replace('</head>', '<script src="/_wcloner/platform-integration.js"></script>\n</head>');
  }
  
  return html;
}

// ============================================================
// FILE RESOLUTION
// ============================================================

function findFile(urlPath, folder) {
  // Remove query params
  urlPath = urlPath.split('?')[0];
  
  // Build full path
  let filePath = path.join(BASE_DIR, folder, urlPath);
  
  // Security: prevent directory traversal
  if (!filePath.startsWith(BASE_DIR)) {
    return null;
  }
  
  // Try exact path
  if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
    return filePath;
  }
  
  // Try with index.html
  if (fs.existsSync(path.join(filePath, 'index.html'))) {
    return path.join(filePath, 'index.html');
  }
  
  // Try with .html extension
  if (fs.existsSync(filePath + '.html')) {
    return filePath + '.html';
  }
  
  return null;
}

// ============================================================
// SERVE FUNCTIONS
// ============================================================

function serveFile(res, filePath, gzip = true) {
  const mimeType = getContentType(filePath);
  const content = fs.readFileSync(filePath);
  
  const headers = {
    'Content-Type': mimeType,
    'Cache-Control': 'public, max-age=3600',
  };
  
  if (gzip && content.length > 1024) {
    zlib.gzip(content, (err, compressed) => {
      if (err) {
        res.writeHead(200, headers);
        res.end(content);
      } else {
        headers['Content-Encoding'] = 'gzip';
        headers['Content-Length'] = compressed.length;
        res.writeHead(200, headers);
        res.end(compressed);
      }
    });
  } else {
    headers['Content-Length'] = content.length;
    res.writeHead(200, headers);
    res.end(content);
  }
}

function serveHtml(res, filePath, folder) {
  let html = fs.readFileSync(filePath, 'utf-8');
  html = rewriteHtml(html, folder);
  
  const buffer = Buffer.from(html, 'utf-8');
  const headers = {
    'Content-Type': 'text/html; charset=utf-8',
    'Cache-Control': 'no-cache',
  };
  
  zlib.gzip(buffer, (err, compressed) => {
    if (err) {
      headers['Content-Length'] = buffer.length;
      res.writeHead(200, headers);
      res.end(buffer);
    } else {
      headers['Content-Encoding'] = 'gzip';
      headers['Content-Length'] = compressed.length;
      res.writeHead(200, headers);
      res.end(compressed);
    }
  });
}

function serve404(res) {
  res.writeHead(404, { 'Content-Type': 'text/html; charset=utf-8' });
  res.end(`<!DOCTYPE html>
<html>
<head><title>404 - Not Found</title></head>
<body style="font-family:sans-serif;text-align:center;padding:50px;">
  <h1>404 - Page Not Found</h1>
  <p>The requested file was not found on this server.</p>
  <p><a href="/">Go to homepage</a></p>
</body>
</html>`);
}

// ============================================================
// HTTP SERVER
// ============================================================

const server = http.createServer((req, res) => {
  const host = req.headers.host || 'localhost';
  const folder = resolveFolder(host);
  let urlPath = decodeURIComponent(req.url.split('?')[0]);
  
  console.log(`[${new Date().toISOString()}] ${req.method} ${host}${urlPath} -> ${folder}`);
  
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  // OPTIONS preflight
  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }
  
  // Serve platform-integration.js from _wcloner directory
  if (urlPath === '/_wcloner/platform-integration.js') {
    const integrationPath = path.join(BASE_DIR, '_wcloner', 'platform-integration.js');
    if (fs.existsSync(integrationPath)) {
      serveFile(res, integrationPath);
    } else {
      serve404(res);
    }
    return;
  }
  
  // Root redirect to index
  if (urlPath === '/' || urlPath === '') {
    urlPath = '/index.html';
  }
  
  // Find file
  const filePath = findFile(urlPath, folder);
  
  if (!filePath) {
    serve404(res);
    return;
  }
  
  // Serve HTML with rewriting
  if (filePath.endsWith('.html') || filePath.endsWith('.htm')) {
    serveHtml(res, filePath, folder);
  } else {
    // Serve static files
    serveFile(res, filePath);
  }
});

server.listen(PORT, () => {
  console.log(`\n========================================`);
  console.log(`🚀 WCLoner Server Started`);
  console.log(`========================================`);
  console.log(`Main domain: ${MAIN_DOMAIN}`);
  console.log(`Local domain: ${LOCAL_DOMAIN}`);
  console.log(`Port: ${PORT}`);
  console.log(`\nOpen in browser:`);
  console.log(`  http://localhost:${PORT}`);
  console.log(`  http://${LOCAL_DOMAIN}:${PORT}`);
  SUBDOMAINS.forEach(sub => {
    const localSub = sub.replace('.' + MAIN_DOMAIN, '.' + LOCAL_DOMAIN);
    console.log(`  http://${localSub}:${PORT}`);
  });
  console.log(`========================================\n`);
});

// Graceful shutdown
process.on('SIGINT', () => {
  console.log('\n[WCLoner Server] Shutting down...');
  server.close(() => {
    console.log('[WCLoner Server] Server closed');
    process.exit(0);
  });
});
